packages:
  - backend
  - contracts
autoInstallPeers: true
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msgpackr-extract: true
  nx: true
  unrs-resolver: true
  workerd: true
  '@nestjs/core': false
  less: true
  '@prisma/engines': true
  prisma: true
  '@scarf/scarf': true
