-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Employee"
(
  employee_id integer NOT NULL,
  firstname character varying(100) COLLATE pg_catalog."default" NOT NULL,
  lastname character varying(100) COLLATE pg_catalog."default" NOT NULL,
  role character varying(30) COLLATE pg_catalog."default" NOT NULL,
  CONSTRAINT "Employee_pkey" PRIMARY KEY (employee_id)
  );

CREATE TABLE IF NOT EXISTS public."Ingredient"
(
  ingredient_id integer NOT NULL,
  name character varying(100) COLLATE pg_catalog."default",
  CONSTRAINT "Ingredient_pkey" PRIMARY KEY (ingredient_id)
  );

CREATE TABLE IF NOT EXISTS public."Order"
(
  order_id integer NOT NULL,
  table_id integer NOT NULL,
  employee_id integer,
  CONSTRAINT "Order_pkey" PRIMARY KEY (order_id)
  );

CREATE TABLE IF NOT EXISTS public."Order_Item"
(
  order_id integer NOT NULL,
  product_id integer NOT NULL,
  order_item_id integer NOT NULL,
  status character varying(30) COLLATE pg_catalog."default" NOT NULL,
  CONSTRAINT "Order_Item_pkey" PRIMARY KEY (order_item_id)
  );

CREATE TABLE IF NOT EXISTS public."Product"
(
  product_id integer NOT NULL,
  description character varying(100) COLLATE pg_catalog."default",
  price numeric NOT NULL DEFAULT 0.0,
  type character varying(50) COLLATE pg_catalog."default" NOT NULL,
  name character varying(100) COLLATE pg_catalog."default" NOT NULL,
  CONSTRAINT "Product_pkey" PRIMARY KEY (product_id)
  );

CREATE TABLE IF NOT EXISTS public."Product_Ingredient"
(
  product_id integer NOT NULL,
  ingredient_id integer NOT NULL,
  amount integer NOT NULL DEFAULT 0,
  CONSTRAINT "Product_Ingredient_pkey" PRIMARY KEY (product_id, ingredient_id)
  );

CREATE TABLE IF NOT EXISTS public."Table"
(
  table_id integer NOT NULL,
  table_number integer NOT NULL,
  seats integer NOT NULL DEFAULT 0,
  CONSTRAINT "Table_pkey" PRIMARY KEY (table_id)
  );

ALTER TABLE IF EXISTS public."Order"
  ADD CONSTRAINT employee_order_fk FOREIGN KEY (employee_id)
  REFERENCES public."Employee" (employee_id) MATCH SIMPLE
  ON UPDATE NO ACTION
     ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Order"
  ADD CONSTRAINT table_order_fk FOREIGN KEY (table_id)
  REFERENCES public."Table" (table_id) MATCH SIMPLE
  ON UPDATE NO ACTION
     ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Order_Item"
  ADD CONSTRAINT order_id_fk FOREIGN KEY (order_id)
  REFERENCES public."Order" (order_id) MATCH SIMPLE
  ON UPDATE NO ACTION
     ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Order_Item"
  ADD CONSTRAINT product_id_fk FOREIGN KEY (product_id)
  REFERENCES public."Product" (product_id) MATCH SIMPLE
  ON UPDATE NO ACTION
     ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Product_Ingredient"
  ADD CONSTRAINT ingredient_id_fk FOREIGN KEY (ingredient_id)
  REFERENCES public."Ingredient" (ingredient_id) MATCH SIMPLE
  ON UPDATE NO ACTION
     ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Product_Ingredient"
  ADD CONSTRAINT product_id_fk FOREIGN KEY (product_id)
  REFERENCES public."Product" (product_id) MATCH SIMPLE
  ON UPDATE NO ACTION
     ON DELETE NO ACTION;

END;
